const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.uid',true),'')::uuid $$;
GRANT USAGE ON SCHEMA auth TO authenticated,anon;
CREATE FUNCTION public.has_role(uuid,text) RETURNS boolean LANGUAGE sql AS $$ SELECT $1='00000000-0000-0000-0000-000000000001'::uuid $$;
CREATE TABLE public.banners(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), titulo text, ativo boolean, ordem integer);
INSERT INTO banners(titulo,ativo,ordem) VALUES('Antigo',true,5);`);
const sql=readFileSync(new URL('../supabase/migrations/20260922120000_banner_companies.sql', import.meta.url),'utf8');await db.exec(sql);
assert.deepEqual((await db.query('SELECT titulo,ativo,ordem,anunciante_id FROM banners')).rows,[{titulo:'Antigo',ativo:true,ordem:5,anunciante_id:null}]);
await db.exec("SET ROLE authenticated; SET request.uid='00000000-0000-0000-0000-000000000001'");
const id=(await db.query("INSERT INTO banner_empresas(nome) VALUES('Madeireira') RETURNING id")).rows[0].id;
assert.equal((await db.query('SELECT * FROM banner_empresas')).rows.length,1);
await assert.rejects(db.exec("INSERT INTO banner_empresas(nome) VALUES(' madeireira ' )"));
await assert.rejects(db.exec("INSERT INTO banner_empresas(nome) VALUES('   ' )"));
await db.exec("SET request.uid='00000000-0000-0000-0000-000000000002'");
assert.equal((await db.query('SELECT * FROM banner_empresas')).rows.length,0);
await assert.rejects(db.exec("INSERT INTO banner_empresas(nome) VALUES('Intruso')"));
await db.exec("DELETE FROM banner_empresas");
await db.exec('RESET ROLE; SET ROLE anon');await assert.rejects(db.exec('SELECT * FROM banner_empresas'));
await db.exec('RESET ROLE');
await db.query('UPDATE banners SET anunciante_id=$1',[id]);
await assert.rejects(db.query('DELETE FROM banner_empresas WHERE id=$1',[id]));
await db.exec(sql);
assert.equal((await db.query('SELECT anunciante_id FROM banners')).rows[0].anunciante_id,id);
assert.equal((await db.query('SELECT count(*)::int AS n FROM banner_empresas')).rows[0].n,1);
console.log('10 verificações passaram: banners antigos, persistência, validação, acesso admin e reaplicação.');await db.close();
