/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RCodigoRouteImport } from './routes/r.$codigo'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppPedidosRouteImport } from './routes/_authenticated/app.pedidos'
import { Route as AuthenticatedAppNotificacoesRouteImport } from './routes/_authenticated/app.notificacoes'
import { Route as AuthenticatedAppEstoqueRouteImport } from './routes/_authenticated/app.estoque'
import { Route as AuthenticatedAppBuscarRouteImport } from './routes/_authenticated/app.buscar'
import { Route as AuthenticatedAppAnunciarRouteImport } from './routes/_authenticated/app.anunciar'
import { Route as AuthenticatedAppAlertasRouteImport } from './routes/_authenticated/app.alertas'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppVendedorIndexRouteImport } from './routes/_authenticated/app.vendedor.index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as AuthenticatedAppMaterialIdRouteImport } from './routes/_authenticated/app.material.$id'
import { Route as AuthenticatedAppEmpresaIdRouteImport } from './routes/_authenticated/app.empresa.$id'
import { Route as AuthenticatedAppAdminPlanosRouteImport } from './routes/_authenticated/app.admin.planos'
import { Route as AuthenticatedAppAdminModeracaoFotosRouteImport } from './routes/_authenticated/app.admin.moderacao-fotos'
import { Route as AuthenticatedAppAdminDenunciasRouteImport } from './routes/_authenticated/app.admin.denuncias'
import { Route as AuthenticatedAppAdminBannersRouteImport } from './routes/_authenticated/app.admin.banners'
import { Route as AuthenticatedAppAdminVendedoresIndexRouteImport } from './routes/_authenticated/app.admin.vendedores.index'
import { Route as AuthenticatedAppAdminEmpresasIndexRouteImport } from './routes/_authenticated/app.admin.empresas.index'
import { Route as AuthenticatedAppAdminVendedoresIdRouteImport } from './routes/_authenticated/app.admin.vendedores.$id'
import { Route as AuthenticatedAppAdminEmpresasIdRouteImport } from './routes/_authenticated/app.admin.empresas.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodigoRoute = RCodigoRouteImport.update({
  id: '/r/$codigo',
  path: '/r/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPedidosRoute = AuthenticatedAppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificacoesRoute =
  AuthenticatedAppNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEstoqueRoute = AuthenticatedAppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBuscarRoute = AuthenticatedAppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnunciarRoute =
  AuthenticatedAppAnunciarRouteImport.update({
    id: '/anunciar',
    path: '/anunciar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlertasRoute = AuthenticatedAppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVendedorIndexRoute =
  AuthenticatedAppVendedorIndexRouteImport.update({
    id: '/vendedor/',
    path: '/vendedor/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppMaterialIdRoute =
  AuthenticatedAppMaterialIdRouteImport.update({
    id: '/material/$id',
    path: '/material/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmpresaIdRoute =
  AuthenticatedAppEmpresaIdRouteImport.update({
    id: '/empresa/$id',
    path: '/empresa/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminPlanosRoute =
  AuthenticatedAppAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminModeracaoFotosRoute =
  AuthenticatedAppAdminModeracaoFotosRouteImport.update({
    id: '/moderacao-fotos',
    path: '/moderacao-fotos',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminDenunciasRoute =
  AuthenticatedAppAdminDenunciasRouteImport.update({
    id: '/denuncias',
    path: '/denuncias',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminBannersRoute =
  AuthenticatedAppAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminVendedoresIndexRoute =
  AuthenticatedAppAdminVendedoresIndexRouteImport.update({
    id: '/vendedores/',
    path: '/vendedores/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminEmpresasIndexRoute =
  AuthenticatedAppAdminEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminVendedoresIdRoute =
  AuthenticatedAppAdminVendedoresIdRouteImport.update({
    id: '/vendedores/$id',
    path: '/vendedores/$id',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminEmpresasIdRoute =
  AuthenticatedAppAdminEmpresasIdRouteImport.update({
    id: '/empresas/$id',
    path: '/empresas/$id',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r/$codigo': typeof RCodigoRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/app/anunciar': typeof AuthenticatedAppAnunciarRoute
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/banners': typeof AuthenticatedAppAdminBannersRoute
  '/app/admin/denuncias': typeof AuthenticatedAppAdminDenunciasRoute
  '/app/admin/moderacao-fotos': typeof AuthenticatedAppAdminModeracaoFotosRoute
  '/app/admin/planos': typeof AuthenticatedAppAdminPlanosRoute
  '/app/empresa/$id': typeof AuthenticatedAppEmpresaIdRoute
  '/app/material/$id': typeof AuthenticatedAppMaterialIdRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/vendedor/': typeof AuthenticatedAppVendedorIndexRoute
  '/app/admin/empresas/$id': typeof AuthenticatedAppAdminEmpresasIdRoute
  '/app/admin/vendedores/$id': typeof AuthenticatedAppAdminVendedoresIdRoute
  '/app/admin/empresas/': typeof AuthenticatedAppAdminEmpresasIndexRoute
  '/app/admin/vendedores/': typeof AuthenticatedAppAdminVendedoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r/$codigo': typeof RCodigoRoute
  '/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/app/anunciar': typeof AuthenticatedAppAnunciarRoute
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/banners': typeof AuthenticatedAppAdminBannersRoute
  '/app/admin/denuncias': typeof AuthenticatedAppAdminDenunciasRoute
  '/app/admin/moderacao-fotos': typeof AuthenticatedAppAdminModeracaoFotosRoute
  '/app/admin/planos': typeof AuthenticatedAppAdminPlanosRoute
  '/app/empresa/$id': typeof AuthenticatedAppEmpresaIdRoute
  '/app/material/$id': typeof AuthenticatedAppMaterialIdRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/vendedor': typeof AuthenticatedAppVendedorIndexRoute
  '/app/admin/empresas/$id': typeof AuthenticatedAppAdminEmpresasIdRoute
  '/app/admin/vendedores/$id': typeof AuthenticatedAppAdminVendedoresIdRoute
  '/app/admin/empresas': typeof AuthenticatedAppAdminEmpresasIndexRoute
  '/app/admin/vendedores': typeof AuthenticatedAppAdminVendedoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r/$codigo': typeof RCodigoRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/_authenticated/app/anunciar': typeof AuthenticatedAppAnunciarRoute
  '/_authenticated/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/_authenticated/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/_authenticated/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/_authenticated/app/pedidos': typeof AuthenticatedAppPedidosRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/banners': typeof AuthenticatedAppAdminBannersRoute
  '/_authenticated/app/admin/denuncias': typeof AuthenticatedAppAdminDenunciasRoute
  '/_authenticated/app/admin/moderacao-fotos': typeof AuthenticatedAppAdminModeracaoFotosRoute
  '/_authenticated/app/admin/planos': typeof AuthenticatedAppAdminPlanosRoute
  '/_authenticated/app/empresa/$id': typeof AuthenticatedAppEmpresaIdRoute
  '/_authenticated/app/material/$id': typeof AuthenticatedAppMaterialIdRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/vendedor/': typeof AuthenticatedAppVendedorIndexRoute
  '/_authenticated/app/admin/empresas/$id': typeof AuthenticatedAppAdminEmpresasIdRoute
  '/_authenticated/app/admin/vendedores/$id': typeof AuthenticatedAppAdminVendedoresIdRoute
  '/_authenticated/app/admin/empresas/': typeof AuthenticatedAppAdminEmpresasIndexRoute
  '/_authenticated/app/admin/vendedores/': typeof AuthenticatedAppAdminVendedoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/auth/callback'
    | '/r/$codigo'
    | '/app/admin'
    | '/app/alertas'
    | '/app/anunciar'
    | '/app/buscar'
    | '/app/estoque'
    | '/app/notificacoes'
    | '/app/pedidos'
    | '/app/perfil'
    | '/app/'
    | '/app/admin/banners'
    | '/app/admin/denuncias'
    | '/app/admin/moderacao-fotos'
    | '/app/admin/planos'
    | '/app/empresa/$id'
    | '/app/material/$id'
    | '/app/admin/'
    | '/app/vendedor/'
    | '/app/admin/empresas/$id'
    | '/app/admin/vendedores/$id'
    | '/app/admin/empresas/'
    | '/app/admin/vendedores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/callback'
    | '/r/$codigo'
    | '/app/alertas'
    | '/app/anunciar'
    | '/app/buscar'
    | '/app/estoque'
    | '/app/notificacoes'
    | '/app/pedidos'
    | '/app/perfil'
    | '/app'
    | '/app/admin/banners'
    | '/app/admin/denuncias'
    | '/app/admin/moderacao-fotos'
    | '/app/admin/planos'
    | '/app/empresa/$id'
    | '/app/material/$id'
    | '/app/admin'
    | '/app/vendedor'
    | '/app/admin/empresas/$id'
    | '/app/admin/vendedores/$id'
    | '/app/admin/empresas'
    | '/app/admin/vendedores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/r/$codigo'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/alertas'
    | '/_authenticated/app/anunciar'
    | '/_authenticated/app/buscar'
    | '/_authenticated/app/estoque'
    | '/_authenticated/app/notificacoes'
    | '/_authenticated/app/pedidos'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/banners'
    | '/_authenticated/app/admin/denuncias'
    | '/_authenticated/app/admin/moderacao-fotos'
    | '/_authenticated/app/admin/planos'
    | '/_authenticated/app/empresa/$id'
    | '/_authenticated/app/material/$id'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/vendedor/'
    | '/_authenticated/app/admin/empresas/$id'
    | '/_authenticated/app/admin/vendedores/$id'
    | '/_authenticated/app/admin/empresas/'
    | '/_authenticated/app/admin/vendedores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  RCodigoRoute: typeof RCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$codigo': {
      id: '/r/$codigo'
      path: '/r/$codigo'
      fullPath: '/r/$codigo'
      preLoaderRoute: typeof RCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pedidos': {
      id: '/_authenticated/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AuthenticatedAppPedidosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notificacoes': {
      id: '/_authenticated/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AuthenticatedAppNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/estoque': {
      id: '/_authenticated/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AuthenticatedAppEstoqueRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/buscar': {
      id: '/_authenticated/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AuthenticatedAppBuscarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/anunciar': {
      id: '/_authenticated/app/anunciar'
      path: '/anunciar'
      fullPath: '/app/anunciar'
      preLoaderRoute: typeof AuthenticatedAppAnunciarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alertas': {
      id: '/_authenticated/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AuthenticatedAppAlertasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vendedor/': {
      id: '/_authenticated/app/vendedor/'
      path: '/vendedor'
      fullPath: '/app/vendedor/'
      preLoaderRoute: typeof AuthenticatedAppVendedorIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/material/$id': {
      id: '/_authenticated/app/material/$id'
      path: '/material/$id'
      fullPath: '/app/material/$id'
      preLoaderRoute: typeof AuthenticatedAppMaterialIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/empresa/$id': {
      id: '/_authenticated/app/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/app/empresa/$id'
      preLoaderRoute: typeof AuthenticatedAppEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/planos': {
      id: '/_authenticated/app/admin/planos'
      path: '/planos'
      fullPath: '/app/admin/planos'
      preLoaderRoute: typeof AuthenticatedAppAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/moderacao-fotos': {
      id: '/_authenticated/app/admin/moderacao-fotos'
      path: '/moderacao-fotos'
      fullPath: '/app/admin/moderacao-fotos'
      preLoaderRoute: typeof AuthenticatedAppAdminModeracaoFotosRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/denuncias': {
      id: '/_authenticated/app/admin/denuncias'
      path: '/denuncias'
      fullPath: '/app/admin/denuncias'
      preLoaderRoute: typeof AuthenticatedAppAdminDenunciasRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/banners': {
      id: '/_authenticated/app/admin/banners'
      path: '/banners'
      fullPath: '/app/admin/banners'
      preLoaderRoute: typeof AuthenticatedAppAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/vendedores/': {
      id: '/_authenticated/app/admin/vendedores/'
      path: '/vendedores'
      fullPath: '/app/admin/vendedores/'
      preLoaderRoute: typeof AuthenticatedAppAdminVendedoresIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/empresas/': {
      id: '/_authenticated/app/admin/empresas/'
      path: '/empresas'
      fullPath: '/app/admin/empresas/'
      preLoaderRoute: typeof AuthenticatedAppAdminEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/vendedores/$id': {
      id: '/_authenticated/app/admin/vendedores/$id'
      path: '/vendedores/$id'
      fullPath: '/app/admin/vendedores/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminVendedoresIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/empresas/$id': {
      id: '/_authenticated/app/admin/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/app/admin/empresas/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminEmpresasIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminBannersRoute: typeof AuthenticatedAppAdminBannersRoute
  AuthenticatedAppAdminDenunciasRoute: typeof AuthenticatedAppAdminDenunciasRoute
  AuthenticatedAppAdminModeracaoFotosRoute: typeof AuthenticatedAppAdminModeracaoFotosRoute
  AuthenticatedAppAdminPlanosRoute: typeof AuthenticatedAppAdminPlanosRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAdminEmpresasIdRoute: typeof AuthenticatedAppAdminEmpresasIdRoute
  AuthenticatedAppAdminVendedoresIdRoute: typeof AuthenticatedAppAdminVendedoresIdRoute
  AuthenticatedAppAdminEmpresasIndexRoute: typeof AuthenticatedAppAdminEmpresasIndexRoute
  AuthenticatedAppAdminVendedoresIndexRoute: typeof AuthenticatedAppAdminVendedoresIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminBannersRoute: AuthenticatedAppAdminBannersRoute,
  AuthenticatedAppAdminDenunciasRoute: AuthenticatedAppAdminDenunciasRoute,
  AuthenticatedAppAdminModeracaoFotosRoute:
    AuthenticatedAppAdminModeracaoFotosRoute,
  AuthenticatedAppAdminPlanosRoute: AuthenticatedAppAdminPlanosRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAdminEmpresasIdRoute: AuthenticatedAppAdminEmpresasIdRoute,
  AuthenticatedAppAdminVendedoresIdRoute:
    AuthenticatedAppAdminVendedoresIdRoute,
  AuthenticatedAppAdminEmpresasIndexRoute:
    AuthenticatedAppAdminEmpresasIndexRoute,
  AuthenticatedAppAdminVendedoresIndexRoute:
    AuthenticatedAppAdminVendedoresIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAlertasRoute: typeof AuthenticatedAppAlertasRoute
  AuthenticatedAppAnunciarRoute: typeof AuthenticatedAppAnunciarRoute
  AuthenticatedAppBuscarRoute: typeof AuthenticatedAppBuscarRoute
  AuthenticatedAppEstoqueRoute: typeof AuthenticatedAppEstoqueRoute
  AuthenticatedAppNotificacoesRoute: typeof AuthenticatedAppNotificacoesRoute
  AuthenticatedAppPedidosRoute: typeof AuthenticatedAppPedidosRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppEmpresaIdRoute: typeof AuthenticatedAppEmpresaIdRoute
  AuthenticatedAppMaterialIdRoute: typeof AuthenticatedAppMaterialIdRoute
  AuthenticatedAppVendedorIndexRoute: typeof AuthenticatedAppVendedorIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAlertasRoute: AuthenticatedAppAlertasRoute,
  AuthenticatedAppAnunciarRoute: AuthenticatedAppAnunciarRoute,
  AuthenticatedAppBuscarRoute: AuthenticatedAppBuscarRoute,
  AuthenticatedAppEstoqueRoute: AuthenticatedAppEstoqueRoute,
  AuthenticatedAppNotificacoesRoute: AuthenticatedAppNotificacoesRoute,
  AuthenticatedAppPedidosRoute: AuthenticatedAppPedidosRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppEmpresaIdRoute: AuthenticatedAppEmpresaIdRoute,
  AuthenticatedAppMaterialIdRoute: AuthenticatedAppMaterialIdRoute,
  AuthenticatedAppVendedorIndexRoute: AuthenticatedAppVendedorIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  RCodigoRoute: RCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
