// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const PASSWORD_RECOVERY_STORAGE_KEY = "sos:password-recovery";

function hasRecoveryMarkerInUrl() {
  if (typeof window === "undefined") return false;

  const search = new URLSearchParams(window.location.search);
  const hash = new URLSearchParams(window.location.hash.replace(/^#/, ""));

  return (
    window.location.pathname === "/auth/redefinir" ||
    search.get("type") === "recovery" ||
    hash.get("type") === "recovery"
  );
}

export function isPasswordRecoveryPending() {
  if (typeof window === "undefined") return false;
  return (
    hasRecoveryMarkerInUrl() ||
    window.sessionStorage.getItem(PASSWORD_RECOVERY_STORAGE_KEY) === "1"
  );
}

export function clearPasswordRecoveryPending() {
  if (typeof window === "undefined") return;
  window.sessionStorage.removeItem(PASSWORD_RECOVERY_STORAGE_KEY);
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure essas variáveis no ambiente do app.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Capture the recovery marker before Supabase consumes and removes the URL hash.
  if (typeof window !== "undefined" && hasRecoveryMarkerInUrl()) {
    window.sessionStorage.setItem(PASSWORD_RECOVERY_STORAGE_KEY, "1");
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  if (typeof window !== "undefined") {
    client.auth.onAuthStateChange((event) => {
      if (event !== "PASSWORD_RECOVERY") return;

      window.sessionStorage.setItem(PASSWORD_RECOVERY_STORAGE_KEY, "1");
      if (window.location.pathname !== "/auth/redefinir") {
        window.location.replace("/auth/redefinir");
      }
    });
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
